In [1]:
pip install nltk

Requirement already satisfied: nltk in c:\programdata\anaconda3\lib\site-packages (3.9.1)
Requirement already satisfied: click in c:\programdata\anaconda3\lib\site-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in c:\programdata\anaconda3\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\programdata\anaconda3\lib\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in c:\programdata\anaconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Import necessary Libraries
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer, PorterStemmer
from nltk import download

In [5]:
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Atul\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Atul\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Atul\AppData\Roaming\nltk_data...
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Atul\AppData\Roaming\nltk_data...

True

In [6]:
import pandas as pd

In [9]:
df = pd.read_csv(r"C:\Users\Atul\Downloads\IMDB Dataset - IMDB Dataset.csv")

In [10]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [11]:
# function to clean text 
# convert lowercase 

def to_lowercase(text):
    return text.lower()

In [14]:
df['cleaned_review'] = df['review'].apply(lambda x :to_lowercase(x))

In [13]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [17]:
# function to remove html tags
def remove_html_tags(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

df['cleaned_data']= df['cleaned_review'].apply(lambda x :remove_html_tags(x))

In [18]:
# function to remove special characters and punctuation
def remove_special_characters(text):
    return re.sub(r'[^a-zA-Z\s]', '', text)

In [19]:
df['cleaned_data'] = df['cleaned_data'].apply(lambda x :remove_special_characters(x))

In [21]:
# Function to remove to numbers 
def remove_numbers(text):
    return re.sub(r'\d+', '', text)

In [23]:
df['cleaned_data'] = df['cleaned_data'].apply(lambda x :remove_numbers(x))

In [24]:
df.head(20)

,review,sentiment,cleaned_review,cleaned_data
0,one of the other reviewers has mentioned that ...,positive,one of the other reviewers has mentioned that ...,one of the other reviewers has mentioned that ...
1,a wonderful little production. <br /><br />the...,positive,a wonderful little production. <br /><br />the...,a wonderful little production the filming tech...
2,i thought this was a wonderful way to spend ti...,positive,i thought this was a wonderful way to spend ti...,i thought this was a wonderful way to spend ti...
3,basically there's a family where a little boy ...,negative,basically there's a family where a little boy ...,basically theres a family where a little boy j...
4,"petter mattei's ""love in the time of money"" is...",positive,"petter mattei's ""love in the time of money"" is...",petter matteis love in the time of money is a ...
5,"probably my all-time favorite movie, a story o...",positive,"probably my all-time favorite movie, a story o...",probably my alltime favorite movie a story of ...
6,i sure would like to see a resurrection of a u...,positive,i sure would like to see a resurrection of a u...,i sure would like to see a resurrection of a u...
7,"this show was an amazing, fresh & innovative i...",negative,"this show was an amazing, fresh & innovative i...",this show was an amazing fresh innovative ide...
8,encouraged by the positive comments about this...,negative,encouraged by the positive comments about this...,encouraged by the positive comments about this...
9,if you like original gut wrenching laughter yo...,positive,if you like original gut wrenching laughter yo...,if you like original gut wrenching laughter yo...
10,phil the alien is one of those quirky films wh...,negative,phil the alien is one of those quirky films wh...,phil the alien is one of those quirky films wh...
11,i saw this movie when i was about 12 when it c...,negative,i saw this movie when i was about 12 when it c...,i saw this movie when i was about when it cam...
12,so im not a big fan of boll's work but then ag...,negative,so im not a big fan of boll's work but then ag...,so im not a big fan of bolls work but then aga...
13,the cast played shakespeare.<br /><br />shakes...,negative,the cast played shakespeare.<br /><br />shakes...,the cast played shakespeareshakespeare losti a...
14,this a fantastic movie of three prisoners who ...,positive,this a fantastic movie of three prisoners who ...,this a fantastic movie of three prisoners who ...
15,"kind of drawn in by the erotic scenes, only to...",negative,"kind of drawn in by the erotic scenes, only to...",kind of drawn in by the erotic scenes only to ...
16,some films just simply should not be remade. t...,positive,some films just simply should not be remade. t...,some films just simply should not be remade th...
17,this movie made it into one of my top 10 most ...,negative,this movie made it into one of my top 10 most ...,this movie made it into one of my top most aw...
18,"i remember this film,it was the first film i h...",positive,"i remember this film,it was the first film i h...",i remember this filmit was the first film i ha...
19,an awful film! it must have been up against so...,negative,an awful film! it must have been up against so...,an awful film it must have been up against som...

In [26]:
#function to remove extaspaces / whitespaces 
def remove_extra_spaces(text):
  return ''.join(text.split())

df['cleaned_data'] = df['cleaned_data'].apply(lambda x :remove_extra_spaces(x))

In [29]:
# function to remove hastages 
def remove_hashtags(text):
    return re.sub(r'#\w+', '', text)

df['cleaned_data'] = df['cleaned_data'].apply(lambda x :remove_hashtags(x))